### ISSUE TITLE
Please add package and cmake configs

### ISSUE THREAD

**Issue by anton-malakhov** [conda-forge/ittapi-feedstock#1]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
there is no package config nor cmake config provided along with the package.
Please add.
<br/>

**Comment by vnlitvinov** [comment]
I don't think it was excluded, more likely it was either not present in the upstream at the moment of making this package, or wasn't explicitly included.

Note that I am no longer maintaining the package
